// libs/angular/feature-sets/src/lib/set-list/set-list.component.ts
import { Component } from '@angular/core';
import { Set } from '@nx-apollo-example/api-interfaces';
import { Observable } from 'rxjs';
import { SetListGQL } from '@nx-apollo-example/angular/data-access';
import { map } from 'rxjs/operators';

@Component({
  selector: 'nx-apollo-example-set-list',
  templateUrl: './set-list.component.html',
  styleUrls: ['./set-list.component.css']
})
export class SetListComponent {
  sets$: Observable<Set[]>;

  constructor(private setListGQL: SetListGQL) {
    this.sets$ = this.setListGQL.watch().valueChanges.pipe(map((result) => result.data.allSets));
  }
}

<ul>
    <li *ngFor="let set of sets$ | async"> {{set.year}} <strong>{{set.name}}</strong> ({{set.numParts}} parts)
</ul>

// libs/react/feature-sets/src/lib/set-list/set-list.tsx
import React from 'react';

import './set-list.css';
import { useSetListQuery } from '@nx-apollo-example/react/data-access';

/* eslint-disable-next-line */
export interface SetListProps {}

export const SetList = (props: SetListProps) => {
  const { loading, error, data } = useSetListQuery();

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error :(</p>;

  return (
    <ul>
      {data.allSets.map(({ id, name, numParts, year }) => (
        <li key={id}>
          {year} - <strong>{name}</strong> ({numParts} parts)
        </li>
      ))}
    </ul>
  );
};

export default SetList;
